apiVersion: v1
kind: Service
metadata:
  name: {{ include "coolkit.name" . }}-peers
spec:
    clusterIP: None
    selector:
        app.kubernetes.io/name: {{ include "coolkit.name" . }}
    ports:
        - name: peer
          port: {{ .Values.service.port }}
          targetPort: http
