apiVersion: v1
kind: Service
metadata:
  name: {{ include "coolkit.name" . }}
  labels:
    {{- include "coolkit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "coolkit.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
